-- Sharbo Auto DMS 4.1 — Security roles and audit log
-- Non-destructive migration
create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text,
  role text not null default 'read_only' check (role in ('admin','sales','finance','read_only')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  action text not null,
  label text,
  details jsonb not null default '{}'::jsonb,
  page text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_user_id_idx on public.audit_logs(user_id);
alter table public.user_roles enable row level security;
alter table public.audit_logs enable row level security;
drop policy if exists "users_read_own_role" on public.user_roles;
create policy "users_read_own_role" on public.user_roles for select to authenticated using (auth.uid()=user_id);
drop policy if exists "owner_can_create_admin_role" on public.user_roles;
create policy "owner_can_create_admin_role" on public.user_roles for insert to authenticated with check (auth.uid()=user_id and lower(coalesce(email,''))='hashem@sharboauto.com' and role='admin');
drop policy if exists "admin_manage_roles" on public.user_roles;
create policy "admin_manage_roles" on public.user_roles for all to authenticated using (exists(select 1 from public.user_roles r where r.user_id=auth.uid() and r.role='admin' and r.active)) with check (exists(select 1 from public.user_roles r where r.user_id=auth.uid() and r.role='admin' and r.active));
drop policy if exists "authenticated_insert_audit" on public.audit_logs;
create policy "authenticated_insert_audit" on public.audit_logs for insert to authenticated with check (auth.uid()=user_id or user_id is null);
drop policy if exists "admin_read_audit" on public.audit_logs;
create policy "admin_read_audit" on public.audit_logs for select to authenticated using (exists(select 1 from public.user_roles r where r.user_id=auth.uid() and r.role='admin' and r.active));
