const sb = window.supabase.createClient(window.SHARBO_SUPABASE_URL, window.SHARBO_SUPABASE_KEY);
let vehicles=[];
const money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD'});
const km=n=>Number(n||0).toLocaleString('fr-CA')+' km';
const image=v=>(v.images&&v.images[0])||'../assets/images/logo.png';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function normalize(row){return {...row,brand:row.make,title:row.title||[row.make,row.model,row.year].filter(Boolean).join(' '),images:(row.vehicle_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>x.image_url)}}
async function requireAuth(){const {data:{session}}=await sb.auth.getSession();document.querySelector('#loginScreen').classList.toggle('hidden',!!session);if(session)await loadVehicles()}
async function loadVehicles(){const {data,error}=await sb.from('vehicles').select('*, vehicle_images(*)').order('created_at',{ascending:false});if(error){setStatus('Erreur Supabase');console.error(error);vehicles=[]}else{vehicles=(data||[]).map(normalize);setStatus('Connecté à Supabase')}renderAll()}
function setStatus(t){document.querySelector('#connectionStatus').textContent=t}
function renderAll(){const total=vehicles.length,available=vehicles.filter(v=>(v.status||'Disponible')==='Disponible').length,sold=vehicles.filter(v=>String(v.status).toLowerCase().includes('vend')).length;statTotal.textContent=total;statAvailable.textContent=available;statSold.textContent=sold;statValue.textContent=money(vehicles.reduce((s,v)=>s+Number(v.price||0),0));recentVehicles.innerHTML=vehicles.slice(0,5).map(v=>`<div class="vehicle-row"><img src="${esc(image(v))}"><div><strong>${esc(v.title)}</strong><small>${km(v.mileage)} · ${esc(v.status||'Disponible')}</small></div><b>${money(v.price)}</b></div>`).join('')||'<p>Aucun véhicule.</p>';renderBars(total);renderInventory()}
function renderBars(total){const groups=['Disponible','Réservé','Vendu'].map(name=>({name,count:vehicles.filter(v=>String(v.status||'Disponible').toLowerCase().startsWith(name.toLowerCase().slice(0,4))).length}));statusBars.innerHTML=groups.map(g=>`<div><div class="bar-label"><span>${g.name}</span><strong>${g.count}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${total?g.count/total*100:0}%"></div></div></div>`).join('')}
function renderInventory(){const q=(inventorySearch?.value||globalSearch?.value||'').toLowerCase(),status=statusFilter?.value||'';const list=vehicles.filter(v=>(!q||`${v.title} ${v.make} ${v.model} ${v.year} ${v.vin}`.toLowerCase().includes(q))&&(!status||v.status===status));inventoryBody.innerHTML=list.map(v=>`<tr><td><div class="car-cell"><img src="${esc(image(v))}"><div><strong>${esc(v.title)}</strong><small>${esc(v.vin||'')}</small></div></div></td><td>${esc(v.year||'')}</td><td>${km(v.mileage)}</td><td>${money(v.price)}</td><td><span class="badge ${String(v.status).toLowerCase().includes('vend')?'sold':''}">${esc(v.status||'Disponible')}</span></td><td><button class="table-btn" onclick="editVehicle('${v.id}')">Modifier</button><button class="table-btn danger" onclick="deleteVehicle('${v.id}')">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="6">Aucun véhicule trouvé.</td></tr>'}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===name));document.querySelector('#page-'+name)?.classList.add('active');document.querySelector('.sidebar').classList.remove('open');history.replaceState(null,'','#'+name)}
function calculate(){const f=new FormData(financeCalculator),n=k=>Number(f.get(k)||0);let principal=n('vehiclePrice')-n('tradeValue')+n('tradeBalance')+n('managementFee')+n('warranty')+n('rdrpm')+n('transit')-n('downPayment');if(f.get('includeTaxes'))principal*=1.14975;principal=Math.max(0,principal);const months=n('term'),ppy=n('frequency'),periods=Math.round(months/12*ppy),rate=n('interestRate')/100/ppy,payment=rate?principal*rate*(1+rate)**periods/((1+rate)**periods-1):(periods?principal/periods:0),total=payment*periods;paymentResult.textContent=money(payment);loanResult.textContent=money(principal);interestResult.textContent=money(Math.max(0,total-principal));costResult.textContent=money(total)}
function openVehicle(v=null){vehicleForm.reset();vehicleForm.elements.id.value=v?.id||'';vehicleModalTitle.textContent=v?'Modifier le véhicule':'Ajouter un véhicule';for(const n of ['title','stock_number','vin','make','model','trim','year','mileage','price','cost','transmission','fuel','color','engine','status','carfax','description_fr','description_en'])if(v&&vehicleForm.elements[n])vehicleForm.elements[n].value=v[n]??'';vehicleForm.elements.featured.checked=!!v?.featured;vehicleFormMessage.textContent='';vehicleModal.classList.add('open')}
window.editVehicle=id=>openVehicle(vehicles.find(v=>v.id===id));
window.deleteVehicle=async id=>{if(!confirm('Supprimer ce véhicule?'))return;const {error}=await sb.from('vehicles').delete().eq('id',id);if(error)alert(error.message);else await loadVehicles()};
async function uploadImages(vehicleId,files){let order=0;for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${vehicleId}/${Date.now()}-${order}.${ext}`;const {error}=await sb.storage.from(window.SHARBO_STORAGE_BUCKET).upload(path,file,{upsert:false});if(error)throw error;const {data}=sb.storage.from(window.SHARBO_STORAGE_BUCKET).getPublicUrl(path);await sb.from('vehicle_images').insert({vehicle_id:vehicleId,image_url:data.publicUrl,cover:order===0,sort_order:order});order++}}
vehicleForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(vehicleForm),id=fd.get('id'),payload={title:fd.get('title'),stock_number:fd.get('stock_number')||null,vin:fd.get('vin')||null,make:fd.get('make'),model:fd.get('model'),trim:fd.get('trim')||null,year:Number(fd.get('year'))||null,mileage:Number(fd.get('mileage'))||0,price:Number(fd.get('price'))||0,cost:Number(fd.get('cost'))||0,transmission:fd.get('transmission')||null,fuel:fd.get('fuel')||null,color:fd.get('color')||null,engine:fd.get('engine')||null,status:fd.get('status')||'Disponible',carfax:fd.get('carfax')||null,description_fr:fd.get('description_fr')||null,description_en:fd.get('description_en')||null,featured:fd.get('featured')==='on'};vehicleFormMessage.textContent='Enregistrement…';let result;if(id)result=await sb.from('vehicles').update(payload).eq('id',id).select().single();else result=await sb.from('vehicles').insert(payload).select().single();if(result.error){vehicleFormMessage.textContent=result.error.message;return}try{const files=[...vehicleForm.elements.images.files];if(files.length)await uploadImages(result.data.id,files);vehicleFormMessage.textContent='Enregistré.';setTimeout(()=>vehicleModal.classList.remove('open'),500);await loadVehicles()}catch(err){vehicleFormMessage.textContent='Véhicule enregistré, mais erreur photo: '+err.message}});
async function importLegacy(){importMessage.textContent='Importation…';const r=await fetch('../data/vehicles.json',{cache:'no-store'}),d=await r.json();let ok=0,skip=0;for(const v of d.vehicles||[]){const payload={title:v.title||v.id,vin:(v.vin||'').trim()||null,make:v.brand||'',model:v.model||'',year:Number(v.year)||null,mileage:Number(v.mileage)||0,price:Number(v.price)||0,transmission:v.transmission||null,fuel:v.fuel||null,status:v.status||'Disponible',carfax:v.carfax||null,description_fr:v.description_fr||null,description_en:v.description_en||null,featured:v.featured!==false};const {data,error}=await sb.from('vehicles').insert(payload).select().single();if(error){skip++;continue}const imgs=(v.images||[]).map((u,i)=>({vehicle_id:data.id,image_url:new URL(u,location.origin).href,cover:i===0,sort_order:i}));if(imgs.length)await sb.from('vehicle_images').insert(imgs);ok++}importMessage.textContent=`${ok} importés, ${skip} ignorés.`;await loadVehicles()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';const fd=new FormData(loginForm),{error}=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)loginError.textContent=error.message;else{loginScreen.classList.add('hidden');await loadVehicles()}});
logoutBtn.addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));document.querySelectorAll('.addVehicleBtn').forEach(b=>b.addEventListener('click',()=>openVehicle()));menuToggle.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));inventorySearch.addEventListener('input',renderInventory);statusFilter.addEventListener('change',renderInventory);globalSearch.addEventListener('input',e=>{inventorySearch.value=e.target.value;showPage('inventory');renderInventory()});financeCalculator.addEventListener('input',calculate);closeVehicleModal.addEventListener('click',()=>vehicleModal.classList.remove('open'));cancelVehicle.addEventListener('click',()=>vehicleModal.classList.remove('open'));importLegacyBtn.addEventListener('click',importLegacy);settingsForm.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('sharboAdminSettings',JSON.stringify(Object.fromEntries(new FormData(settingsForm))));settingsSaved.textContent='Paramètres enregistrés sur cet appareil.'});
document.addEventListener('DOMContentLoaded',()=>{showPage(location.hash.replace('#','')||'dashboard');calculate();requireAuth()});
