let vehicles=[];
const money=n=>Number(n||0).toLocaleString('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2});
const km=n=>Number(n||0).toLocaleString('fr-CA')+' km';
const image=c=>(c.images&&c.images[0])||'../assets/images/logo.png';
async function loadVehicles(){try{const r=await fetch('../data/vehicles.json',{cache:'no-store'});const d=await r.json();vehicles=d.vehicles||[]}catch(e){console.error(e);vehicles=[]}renderAll()}
function renderAll(){const total=vehicles.length,available=vehicles.filter(v=>(v.status||'Disponible')==='Disponible').length,sold=vehicles.filter(v=>String(v.status).toLowerCase().includes('vend')).length;document.querySelector('#statTotal').textContent=total;document.querySelector('#statAvailable').textContent=available;document.querySelector('#statSold').textContent=sold;document.querySelector('#statValue').textContent=money(vehicles.reduce((s,v)=>s+Number(v.price||0),0));document.querySelector('#recentVehicles').innerHTML=vehicles.slice(-5).reverse().map(v=>`<div class="vehicle-row"><img src="${image(v)}"><div><strong>${v.title||''}</strong><small>${km(v.mileage)} · ${v.status||'Disponible'}</small></div><b>${money(v.price)}</b></div>`).join('')||'<p>Aucun véhicule.</p>';renderBars(total);renderInventory()}
function renderBars(total){const groups=['Disponible','Réservé','Vendu'].map(name=>({name,count:vehicles.filter(v=>String(v.status||'Disponible').toLowerCase().startsWith(name.toLowerCase().slice(0,4))).length}));document.querySelector('#statusBars').innerHTML=groups.map(g=>`<div><div class="bar-label"><span>${g.name}</span><strong>${g.count}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${total?g.count/total*100:0}%"></div></div></div>`).join('')}
function renderInventory(){const q=(document.querySelector('#inventorySearch')?.value||document.querySelector('#globalSearch')?.value||'').toLowerCase();const status=document.querySelector('#statusFilter')?.value||'';const list=vehicles.filter(v=>(!q||`${v.title} ${v.brand} ${v.model} ${v.year} ${v.vin}`.toLowerCase().includes(q))&&(!status||v.status===status));document.querySelector('#inventoryBody').innerHTML=list.map(v=>`<tr><td><div class="car-cell"><img src="${image(v)}"><div><strong>${v.title||''}</strong><small>${v.vin||''}</small></div></div></td><td>${v.year||''}</td><td>${km(v.mileage)}</td><td>${money(v.price)}</td><td><span class="badge ${String(v.status).toLowerCase().includes('vend')?'sold':''}">${v.status||'Disponible'}</span></td><td><a href="../vehicle.html?id=${encodeURIComponent(v.id)}" target="_blank">Voir</a></td></tr>`).join('')||'<tr><td colspan="6">Aucun véhicule trouvé.</td></tr>'}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===name));document.querySelector('#page-'+name)?.classList.add('active');document.querySelector('.sidebar').classList.remove('open');history.replaceState(null,'','#'+name)}
function calculate(){const f=new FormData(document.querySelector('#financeCalculator'));const n=k=>Number(f.get(k)||0);let principal=n('vehiclePrice')-n('tradeValue')+n('tradeBalance')+n('managementFee')+n('warranty')+n('rdrpm')+n('transit')-n('downPayment');if(f.get('includeTaxes'))principal*=1.14975;principal=Math.max(0,principal);const months=n('term');const periodsPerYear=n('frequency');const years=months/12;const totalPeriods=Math.round(years*periodsPerYear);const rate=n('interestRate')/100/periodsPerYear;const payment=rate?principal*rate*Math.pow(1+rate,totalPeriods)/(Math.pow(1+rate,totalPeriods)-1):(totalPeriods?principal/totalPeriods:0);const total=payment*totalPeriods;document.querySelector('#paymentResult').textContent=money(payment);document.querySelector('#loanResult').textContent=money(principal);document.querySelector('#interestResult').textContent=money(Math.max(0,total-principal));document.querySelector('#costResult').textContent=money(total)}
function setupSettings(){const form=document.querySelector('#settingsForm');const saved=JSON.parse(localStorage.getItem('sharboAdminSettings')||'{}');Object.entries(saved).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});form.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('sharboAdminSettings',JSON.stringify(Object.fromEntries(new FormData(form))));document.querySelector('#settingsSaved').textContent='Paramètres enregistrés sur cet appareil.'})}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));document.querySelector('#menuToggle').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelector('#inventorySearch').addEventListener('input',renderInventory);document.querySelector('#statusFilter').addEventListener('change',renderInventory);document.querySelector('#globalSearch').addEventListener('input',e=>{document.querySelector('#inventorySearch').value=e.target.value;showPage('inventory');renderInventory()});document.querySelector('#financeCalculator').addEventListener('input',calculate);setupSettings();showPage(location.hash.replace('#','')||'dashboard');loadVehicles();calculate()});
