/* Sharbo Auto DMS 5.1.2 — Employés & permissions, création directe */
(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const groups=[
 {name:'Tableau de bord',items:[['dashboard.view','Voir le tableau de bord'],['dashboard.financials','Voir profits et chiffres financiers']]},
 {name:'Inventaire',items:[['inventory.view','Voir inventaire'],['inventory.create','Ajouter une voiture'],['inventory.edit','Modifier une voiture'],['inventory.delete','Supprimer / archiver'],['inventory.costs','Voir coûts et profits']]},
 {name:'Clients & ventes',items:[['customers.view','Voir clients'],['customers.manage','Ajouter / modifier clients'],['contracts.view','Voir contrats'],['contracts.manage','Créer / modifier contrats'],['sales.deliver','Livrer un véhicule'],['payments.manage','Gérer paiements']]},
 {name:'Rapports & opérations',items:[['reports.view','Voir rapports'],['reports.financials','Voir rapports financiers'],['operations.view','Voir Opérations'],['operations.manage','Publier, importer, prix et coûts'],['backup.manage','Sauvegarde / restauration']]},
 {name:'Marketing',items:[['marketing.view','Voir Marketing'],['marketing.manage','Créer et modifier les campagnes']]},
 {name:'Administration',items:[['settings.view','Voir paramètres'],['settings.manage','Modifier paramètres'],['staff.view','Voir employés'],['staff.manage','Ajouter et gérer employés'],['audit.view','Voir journal d’audit']]}
];
const all=groups.flatMap(g=>g.items.map(x=>x[0]));
const presets={
 admin:all,
 sales:['dashboard.view','inventory.view','inventory.create','inventory.edit','customers.view','customers.manage','contracts.view','contracts.manage','sales.deliver','payments.manage','operations.view','marketing.view','marketing.manage'],
 finance:['dashboard.view','dashboard.financials','inventory.view','inventory.costs','customers.view','contracts.view','contracts.manage','payments.manage','reports.view','reports.financials','operations.view'],
 read_only:['dashboard.view','inventory.view','customers.view','contracts.view','reports.view'], custom:[]
};
let current={role:'read_only',permissions:[],active:true,isOwner:false}; let staff=[];
function renderPermissions(selected=[]){const host=$('#permissionGrid51');if(!host)return;host.innerHTML=groups.map(g=>`<fieldset><legend>${esc(g.name)}</legend>${g.items.map(([k,l])=>`<label><input type="checkbox" name="perm" value="${k}" ${selected.includes(k)?'checked':''}> <span>${esc(l)}</span></label>`).join('')}</fieldset>`).join('')}
function permissionLabel(n){return n===all.length?'Accès complet':`${n} permission${n>1?'s':''}`}
function can(p){return current.isOwner||current.role==='admin'||current.permissions.includes(p)} window.dmsCan=can;
function applyAccess(){
 $$('[data-permission]').forEach(el=>{const ok=can(el.dataset.permission);el.hidden=!ok;el.classList.toggle('permission-hidden51',!ok)});
 const pageMap={dashboard:'dashboard.view',inventory:'inventory.view',customers:'customers.view',contracts:'contracts.view',salesfiles:'contracts.view',reports:'reports.view',backup:'backup.manage',operations:'operations.view',settings:'settings.view',staff:'staff.view'};
 $$('.nav-link[data-page]').forEach(b=>{const p=pageMap[b.dataset.page];if(p)b.hidden=!can(p)});
 const financialSelectors=['#totalProfit','#dashboardProfit','#costAnalyzer40','#page-reports .profit-card','.profit-cell','.cost-cell']; if(!can('dashboard.financials')&&!can('inventory.costs')) financialSelectors.forEach(s=>$$(`${s}`).forEach(x=>x.classList.add('secure-hidden51')));
 const rules=[['#addVehicleBtn','inventory.create'],['#settingsForm','settings.manage'],['#importLegacyBtn','backup.manage']]; rules.forEach(([s,p])=>$$(`${s} button, ${s}`).forEach(x=>{if(!can(p)){x.disabled=true;x.title='Permission requise'}}));
 document.body.dataset.staffRole=current.role;
}
async function authHeader(){const {data}=await sb.auth.getSession();return {'Content-Type':'application/json','Authorization':`Bearer ${data.session?.access_token||''}`}}
async function callAdmin(body){const r=await fetch('/.netlify/functions/staff-admin',{method:'POST',headers:await authHeader(),body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Erreur serveur');return j}
async function loadCurrent(){try{const {data:{user}}=await sb.auth.getUser();if(!user)return;const owner=(user.email||'').toLowerCase()==='hashem@sharboauto.com';const {data}=await sb.from('staff_profiles').select('*').eq('user_id',user.id).maybeSingle();current={role:data?.role||(owner?'admin':'read_only'),permissions:data?.permissions||presets[data?.role]||[],active:data?.active!==false,isOwner:owner};if(!current.active){await sb.auth.signOut();location.reload();return}applyAccess();}catch(e){console.warn(e)}}
async function loadStaff(){const body=$('#staffBody51');if(!body||!can('staff.view'))return;body.innerHTML='<tr><td colspan="6">Chargement…</td></tr>';try{const {data,error}=await sb.from('staff_profiles').select('*').order('created_at');if(error)throw error;staff=data||[];renderStaff()}catch(e){body.innerHTML=`<tr><td colspan="6">${esc(e.message)} — exécutez le SQL 5.1.</td></tr>`}}
function renderStaff(){const body=$('#staffBody51');const roleNames={admin:'Administrateur',sales:'Ventes',finance:'Finance',read_only:'Lecture seule',custom:'Personnalisé'};body.innerHTML=staff.map(x=>`<tr><td><strong>${esc(x.full_name||'Sans nom')}</strong><small>${esc(x.email||'')}</small></td><td><span class="badge">${esc(roleNames[x.role]||x.role)}</span></td><td>${permissionLabel((x.permissions||[]).length)}</td><td><span class="staff-status51 ${x.active?'active':'inactive'}">${x.active?'Actif':'Suspendu'}</span></td><td>${new Date(x.updated_at||x.created_at).toLocaleString('fr-CA')}</td><td>${can('staff.manage')?`<button class="table-btn" data-edit-staff="${x.user_id}">Modifier</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">Aucun employé.</td></tr>';$('#staffActive51').textContent=staff.filter(x=>x.active).length;$('#staffAdmins51').textContent=staff.filter(x=>x.role==='admin'&&x.active).length;$('#staffInactive51').textContent=staff.filter(x=>!x.active).length}
function openStaff(x=null){const f=$('#staffForm51');f.reset();$('#staffCredentials51')&&($('#staffCredentials51').hidden=true,$('#staffCredentials51').innerHTML='');f.elements.user_id.value=x?.user_id||'';f.elements.full_name.value=x?.full_name||'';f.elements.email.value=x?.email||'';f.elements.email.readOnly=!!x;if(f.elements.temporary_password){f.elements.temporary_password.closest('label').hidden=!!x;f.elements.temporary_password.required=!x;f.elements.temporary_password.value=x?'':makeTempPassword()}f.elements.phone.value=x?.phone||'';f.elements.role.value=x?.role||'sales';f.elements.active.checked=x?.active!==false;renderPermissions(x?.permissions||presets[x?.role||'sales']);$('#staffModalTitle51').textContent=x?'Modifier l’employé':'Ajouter un employé';$('#staffMessage51').textContent='';$('#staffModal51').classList.add('open')}
function makeTempPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$';let out='';crypto.getRandomValues(new Uint32Array(14)).forEach(n=>out+=chars[n%chars.length]);return out}
function showCredentials(email,password){const box=$('#staffCredentials51');if(!box)return;box.hidden=false;box.innerHTML=`<strong>Compte créé.</strong><br>Courriel : <code>${esc(email)}</code><br>Mot de passe temporaire : <code id="tempPassword51">${esc(password)}</code><br><button type="button" id="copyCredentials51">Copier les accès</button><p class="muted">Remettez ces accès à l’employé de façon sécurisée. Il pourra changer son mot de passe après connexion.</p>`;$('#copyCredentials51')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(`Courriel: ${email}\nMot de passe temporaire: ${password}`);$('#copyCredentials51').textContent='Copié ✓'})}
async function saveStaff(e){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),user_id=fd.get('user_id'),password=fd.get('temporary_password')||'',payload={user_id:user_id||undefined,email:fd.get('email').trim().toLowerCase(),full_name:fd.get('full_name').trim(),phone:fd.get('phone').trim()||null,role:fd.get('role'),active:fd.get('active')==='on',permissions:fd.getAll('perm'),temporary_password:password};$('#staffMessage51').textContent='Enregistrement…';try{const res=await callAdmin({action:user_id?'update':'create',staff:payload});$('#staffMessage51').textContent=user_id?'Employé mis à jour.':'Compte employé créé.';if(!user_id)showCredentials(payload.email,res.temporary_password||password);window.dmsAudit?.(user_id?'staff_update':'staff_create',`${payload.full_name} — ${payload.role}`,{email:payload.email});await loadStaff();if(user_id)setTimeout(()=>$('#staffModal51').classList.remove('open'),700)}catch(err){$('#staffMessage51').textContent=err.message}}
async function init(){document.body.dataset.staffVersion='5.1.2';renderPermissions(presets.sales);await loadCurrent();$('#addStaffBtn51')?.addEventListener('click',()=>openStaff());$('#refreshStaff51')?.addEventListener('click',loadStaff);$('#staffForm51')?.addEventListener('submit',saveStaff);$('#staffForm51 [name=role]')?.addEventListener('change',e=>renderPermissions(presets[e.target.value]||[]));$('#selectAllPermissions51')?.addEventListener('click',()=>{const boxes=$$('#permissionGrid51 input');const on=boxes.some(x=>!x.checked);boxes.forEach(x=>x.checked=on)});document.addEventListener('click',e=>{if(e.target.matches('[data-close-staff51]'))$('#staffModal51').classList.remove('open');const id=e.target.dataset.editStaff;if(id)openStaff(staff.find(x=>x.user_id===id))});await loadStaff()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1100));else setTimeout(init,1100);
})();
